repos:
  - repo: local
    hooks:
      - id: typescript-lint
        name: just lint ts
        entry: just lint ts
        language: system
        pass_filenames: false
        stages: [commit]
      - id: rust-check
        name: just check rust
        entry: just check rust
        language: system
        pass_filenames: false
        stages: [commit]
