packages:
  - apps/docs
  - apps/email-playground
  - apps/proxy
  - apps/recorder
  - apps/webui
  - packages/email
  - packages/testing
allowBuilds:
  "@j178/prek": true
  "@parcel/watcher": true
  "@tailwindcss/oxide": true
  bufferutil: true
  core-js: true
  esbuild: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - '@ark/schema@0.56.4'
  - '@ark/util@0.56.4'
  - '@vitest/mocker@5.0.2'
  - '@vitest/spy@5.0.2'
  - arkregex@0.0.10
  - arktype@2.2.5
  - vitest@5.0.2
overrides:
  codemirror-graphql>@codemirror/language: "^6.12.4"
