packages:
  - apps/docs
  - apps/email-playground
  - apps/proxy
  - apps/recorder
  - apps/webui
  - packages/email
  - packages/testing
allowBuilds:
  "@j178/prek": true
  "@parcel/watcher": true
  "@tailwindcss/oxide": true
  bufferutil: true
  core-js: true
  esbuild: true
  utf-8-validate: true
overrides:
  codemirror-graphql>@codemirror/language: "^6.11.1"
