// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EchoTaskInput = {
  taskId: string;
  subscriberId?: number | null;
  cronId?: number | null;
};
