// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Versioned business preset; legacy libjxl numeric knobs have no equivalent.
 */
export type EncodeJxlOptions = { presetVersion: number, };
