// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncodeAvifOptions } from "./EncodeAvifOptions";
import type { EncodeJxlOptions } from "./EncodeJxlOptions";
import type { EncodeWebpOptions } from "./EncodeWebpOptions";

export type EncodeImageOptions =
  | ({ mimeType: "image/webp" } & EncodeWebpOptions)
  | ({ mimeType: "image/avif" } & EncodeAvifOptions)
  | ({ mimeType: "image/jxl" } & EncodeJxlOptions);
