// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncodeImageOptions } from "./EncodeImageOptions";

export type OptimizeImageTaskInput = {
	sourcePath: string;
	targetPath: string;
	formatOptions: EncodeImageOptions;
	subscriberId?: number | null;
	cronId?: number | null;
};
