// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EchoTask } from "./EchoTask";
import type { OptimizeImageTask } from "./OptimizeImageTask";

export type SystemTaskType =
	| ({ taskType: "optimize_image" } & OptimizeImageTask)
	| ({ taskType: "test" } & EchoTask);
