// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EchoTaskInput } from "./EchoTaskInput";
import type { OptimizeImageTaskInput } from "./OptimizeImageTaskInput";

export type SystemTaskInput =
  | ({ taskType: "optimize_image" } & OptimizeImageTaskInput)
  | ({ taskType: "test" } & EchoTaskInput);
